### ISSUE TITLE
Error in as.double(y) with plot

### ISSUE THREAD

**Issue by gianfilippo** [Japrin/STARTRAC#7]
Hi,

I am reporting the same error as another user.

when i run "plot(out,index.type="cluster.all",byPatient=F)", it happend to me "Error in as.double(y) : cannot coerce type 'S4' to vector of type 'double'". Someone can tell me how to resolve it?

I follow the step by step approach
      obj <- new("Startrac",processed,aid="all")
      obj <- calIndex(obj)
      obj <- pIndex(obj)
where processed is a data.frame as required.

I also tried running the function
obj <- suppressWarnings(Startrac.run(processed, proj = "all", cores = NULL, n.perm = NULL, verbose = T))

The results is then same

Thanks

**Comment by gianfilippo** [comment]
Hi,

I should add that I also went through the entire step by step approach, following your Startrac.run function.

Also, I see in the object the results for each individual. How do you derive the "total" or anyway the default object ? it does not seem to be the average index for each individual

Thanks

**Comment by Japrin** [comment]
Hi gianfilippo,

I think the bug has been fixed in the updated version.  Hope you can try it again. Welcome any comments and reports.

Best Regards

**Comment by Maojie6509** [comment]
HI

I have reinstalled the latest version . But when i run "plot(out,index.type="cluster.all",byPatient=F)", The following error will still occur "Error in as.double(y) : cannot coerce type 'S4' to vector of type 'double'". 


Thanks

**Comment by Joysaikouda** [comment]
ME too， how can I fix it z （x x）
